name: Fetch Res

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean

jobs:
  Fetch-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Checkout tools repo
        uses: actions/checkout@v6
        with:
          repository: PaiGramTeam/hsr-optimizer
          path: hsr-optimizer

      - name: Set up Python
        uses: astral-sh/setup-uv@v7

      - uses: actions/setup-node@v6
        with:
          node-version: '22.13.0'

      - name: Install Dependencies
        run: |
          uv sync --all-extras --python=3.12

      - name: Fetch Remote Files
        run: |
          uv run compiler/main.py
          npm install
          npm run export
          uv run ruff format .

      - name: Test New files
        if: ${{ inputs.skip-tests == false }}
        run: |
          uv run pytest

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit changes
        run: |
          git add .
          git commit -S -m ":bento: Update res"
          git push
